version: "3"

volumes:
  api_db_data:

services:
  webpage:
    build: ./webpage
    working_dir: /code
    command: mix phx.server
    volumes:
      - ./webpage:/code
    ports:
      - "80:4000"

  api:
    build: ./api
    working_dir: /code
    command: mix phx.server
    volumes:
      - ./api:/code
    ports:
      - "4000:4000"
    links:
      - postgres:postgres.link

  postgres:
    image: postgres:9.6
    volumes:
      - api_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    ports:
      - "5432:5432"
